apiVersion: v1
clusters:
- cluster:
    server: https://440863AD75FBA660CFFF4D036ADC3546.yl4.ap-northeast-2.eks.amazonaws.com
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJd01EWXdNVEEyTWpjeU1Gb1hEVE13TURVek1EQTJNamN5TUZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBSzV4CmJYZlhaQjRLY0tLZmhUM2FmTmIwL0lMdlNHcTdjZTVGTlBmMy9WZzZhaVJmNmNRdzNieUJDRTBua1VZWFJyTEMKNE9tZUNraGNmY1JNSmg4dGM5NStVQVlrbE1nRysydFhtSmdBMGppVXduVWtwRXZabTF2Nng4bDlFOStWaWxVLwpJUjh1alQwaE03M0p1cEQrSUxBbHB6aSt5dlJ5bHFiS08rUEdBbmx0QnNBS1VtS2NGYVVGUlZQNTdEeVNUTGlNCmVkNUl5Zm81eVd1eTZDaXZCZmxUZU9RbmFQdXdvb2kyWTU5dmdiRUNHNzF1bndNSFFuZ0x4eVFxRTQ4YnJqa2IKbDJlVS9pQmdsRmNhNXYyQnkyOEJ5Z2txeG1vMVRGVmNEdFZTV1lobVlHSFVDeVVsTjQ1bG02UDRYQitoZzd3bQoyUEZKL1lhM2E4MDlZVytLY0swQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFCWCtlNHZCeFFYYlU3WHF3L29tQTA3WU8ydSsKbURlUVpTTE5FeDZrNU9FcTFRRnJhYVgvK0s1dVBrYWZVR29BbUU3YkFsMlkzVHRteXFaSmhjeTE5L0hSTXhKSwpzZ3p4M0pqTkw5Q1pvR25ZTVQzR2MxVXRqUXB2U2xVclRoWkFJUUVQQmw4angraGg0UnNvTmYvaGNoSW9FVzZoClF6OUFRZ0JPdkxrazlxeDRsYkVLM1NxdlU0N0t4KzJOV09UQUpxb3ZUMVozaEh5RmNSYVhlZU5TYTlhRW5Ndy8KUTQvS012UDc2blpKUlhlMnZJaXlscXYvVFhBWXVRbjAzbllFQkRRODN2YjhoVklIMUVqMmo5d2xzRnlXVkkrVAoxbXBEYjdhR1F1VVA2NVVVaTY4cnR2cTg4UjYwY0RLaTl5VlQ5aVRHSGlvaisrRi91TSs5WFZ6SVhGbz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: aws
  name: aws
current-context: aws
kind: Config
preferences: {}
users:
- name: aws
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: aws-iam-authenticator
      args:
        - "token"
        - "-i"
        - "kuberkuber"
